name: verify
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  call-verify:
    uses: yai-labs/yai-infra/.github/workflows/reusable-verify.yml@main
    with:
      org: yai-labs
      project_number: 5
      python: false
    secrets: inherit
